version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/deploy/ThreeGoodThings-API
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  Install:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
