version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/deploy/ThreeGoodThings-API
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  AfterInstall:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
