name: AWS Code Deploy

on:
  push:
    branches: [main, fix/code-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Set AWS region
        run: aws configure set region ap-northeast-1

      - name: Run AWS CodeDeploy
        run: aws deploy create-deployment --application-name "ThreeGoodThings-API" --deployment-group-name "code-deploy-deploygroup" --github-location repository="CC-positive/ThreeGoodThings-API",commitId="${{ github.sha }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
