name: Node.js/postgres CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:12.19.1-buster

    sercies:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
